config/routes.rb
Rails.application.routes.draw do
  root "calls#index"
  resources :calls
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call.rb
class Call < ApplicationRecord

  belongs_to :type, -> {select :name}, class_name: 'Plan', foreign_key: :plan_id


end

app/models/plan.rb
class Plan < ApplicationRecord

  def self.update
    self.delete_all

    Plan.create([

                  {id: 01, name: 'Nenhum', data_refer: 'calls.plan'},
                  {id: 30, name: 'FaleMais 30', data_refer: 'calls.plan'},
                  {id: 60, name: 'FaleMais 60', data_refer: 'calls.plan'},
                  {id: 120, name: 'FaleMais 120', data_refer: 'calls.plan'}

                ])

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :set_call, only: %i[ show edit update destroy ]

  # GET /calls or /calls.json
  def index
    @calls = Call.all
    @plans = Plan.all
  end

  # GET /calls/1 or /calls/1.json
  def show
     id = @call.plan_id
     @plan = Plan.find(id)
     @plan = @plan.name
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls or /calls.json
  def create

    fees = fees(params[:call][:origin], params[:call][:destiny])
    puts fees
    puts fees
    puts fees
    valuewithplan = valuewithplan(fees, params[:call][:minuts].to_i, params[:call][:plan_id].to_i)
    valuewithoutplan = valuewithoutplan(fees, params[:call][:minuts].to_i)

    @call = Call.new(
      origin: params[:call][:origin],
      destiny: params[:call][:destiny],
      minuts: params[:call][:minuts],
      valuewithplan: valuewithplan,
      valuewithoutplan: valuewithoutplan,
      plan_id: params[:call][:plan_id]

    )

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: "Call was successfully created." }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  def fees origin, destiny

    if origin == '011'
      if destiny == '016'
        fees = 1.9
      else
        if destiny == '017'
          fees = 1.7
        else
          fees = 0.9
        end
      end
    else
      if origin == '016'
        fees = 2.9
      else
        if origin == '017'
          fees = 2.7
        else
          fees = 1.9
        end
      end
    end
    return fees
  end

  def valuewithplan fees, minuts, plan
    if minuts <= plan
      value = 0.00
    else
      if plan == 30
        additionals = minuts - 30
        value = ((additionals * fees) + ((additionals * fees)*0.10))
      else
        if plan == 60
          additionals = minuts - 60
          value = additionals * fees + (additionals * fees)*0.10
        else
          additionals = minuts - 120
          value = additionals * fees + (additionals * fees)*0.10
        end
      end
    end
    return value

  end

  def valuewithoutplan fees, minuts

    value = fees * minuts;
    return value
  end

  # PATCH/PUT /calls/1 or /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to @call, notice: "Call was successfully updated." }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1 or /calls/1.json
  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url, notice: "Call was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def call_params
      params.require(:call).permit(:origin, :destiny, :minuts)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.erb
<div class="ui middle aligned center aligned grid three columns">
<div class="fice wide column">

  <h3 class="ui header"> Digite os dados da ligação que deseja simular: </h3>
<%= form_with model: call, local: true, html: {class: 'ui form'} do |form| %>

  <% if call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
        <% call.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "two fields">
  <div class="ui field">
    <%= form.label :origin, 'Origem' %>
    <%= form.select :origin, [['011', '011'], ['016', '016'], ['017', '017'], ['018', '018']] %>
  </div>

  <div class="ui field">
    <%= form.label :destiny, 'Destino' %>
    <%= form.select :destiny, [['011', '011'], ['016', '016'], ['017', '017'], ['018', '018']] %>
  </div>
</div>

  <div class="field">
  <div class="ui field">
    <%= form.label :Tempo %>
    <%= form.number_field :minuts %>
  </div>
  </div>

  <div class="field">
  <div class="ui field">
    <label> Plano Utilizado:</label>
    <%= form.select :plan_id, [['Nenhum', '01'], ['FaleMais30', '30'], ['FaleMais 60', '60'], ['FaleMais 120', '60']] %>
  </div>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar', class: 'ui  button positive fluid' %>
  </div>
<% end %>
</div>
</div>

app/views/calls/edit.html.erb
<h1>Editing Call</h1>

<%= render 'form', call: @call %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<br/>
</br/>

<div class="ui middle aligned center aligned grid three columns">
  <div class="fice wide column">
      <h2>Simule sua ligação</h2>
      <div class="ui huge primary button"><%= link_to 'Nova ligação', new_call_path %> <i class="right arrow icon"></i></div>
    </div>
  </div>
</div>

app/views/calls/new.html.erb
<br/>


    <%= render 'form', call: @call %>

    <%= link_to 'Back', calls_path %>

app/views/calls/show.html.erb
<div class="ui middle aligned center aligned grid three columns">
  <div class="fice wide column">

<table class="ui celled striped table">
  <thead>
  <tr>
    <th>Origem</th>
    <th>Destino</th>
    <th>Tempo</th>
    <th>Plano FaleMais</th>
    <th>Com FaleMais</th>
    <th>Sem FaleMais</th>
    <th colspan="6"></th>
  </tr>
  </thead>

  <tbody>

    <tr>
      <td><%= @call.origin %></td>
      <td><%= @call.destiny %></td>
      <td><%= @call.minuts %></td>
      <td> <%= @plan %></td>
      <td>$ <%= @call.valuewithplan %></td>
      <td>$ <%= @call.valuewithoutplan %></td>
      <td><%= link_to 'Edit', edit_call_path(@call) %></td>
      <td><%= link_to 'Destroy', @call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Back', calls_path %></td>
    </tr>

  </tbody>
</table>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Callsystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>